### ISSUE TITLE
与腾讯视频app冲突。

### ISSUE THREAD

**Issue by JerryYangHub** [iTXTech/Daedalus#12]
打开最新版的腾讯视频app，几秒后，vpn会直接关闭。

**Comment by PeratX** [comment]
等考完期末考会在虚拟环境中调查一下tx软件。

**Comment by PeratX** [comment]
可以上传一下【日志】的内容吗

**Comment by PeratX** [comment]
这边无法测试（复现）您所汇报的情况，请于 2017-6-16 23:59 前提供更多信息。

**Comment by JerryYangHub** [comment]
问题主要是出现在：设置中开启高级系统设置，选择了本地规则解析的时候。
【日志】
2017-06-15 15:41:35 [INFO] Daedalus VPN service has stopped
2017-06-15 15:41:35 [ERROR] java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String java.lang.CharSequence.toString()' on a null object reference
	at de.measite.minidns.util.InetAddressUtil.ipv4From(InetAddressUtil.java:23)
	at org.itxtech.daedalus.provider.UdpDnsProvider.handleDnsRequest(UdpDnsProvider.java:317)
	at org.itxtech.daedalus.provider.UdpDnsProvider.readPacketFromDevice(UdpDnsProvider.java:208)
	at org.itxtech.daedalus.provider.UdpDnsProvider.process(UdpDnsProvider.java:150)
	at org.itxtech.daedalus.service.DaedalusVpnService.run(DaedalusVpnService.java:237)
	at java.lang.Thread.run(Thread.java:762)

2017-06-15 15:41:33 [INFO] DnsProvider: Resolving mazu.3g.qq.com  Sending to /115.159.220.214
2017-06-15 15:41:32 [INFO] DnsProvider: Resolving mcgi.v.qq.com  Sending to /115.159.220.214
2017-06-15 15:41:32 [INFO] DnsProvider: Resolving downloadtpt.qqlive.qq.com  Sending to /115.159.220.214
2017-06-15 15:41:32 [INFO] DnsProvider: Resolving mdevstat.qqlive.qq.com  Sending to /115.159.220.214
2017-06-15 15:41:32 [INFO] DnsProvider: Resolving masdk.3g.qq.com  Sending to /115.159.220.214
2017-06-15 15:41:31 [INFO] DnsProvider: Resolving yun-hl.3g.qq.com  Sending to /115.159.220.214
2017-06-15 15:41:31 [INFO] DnsProvider: Resolving pingma.qq.com  Sending to /115.159.220.214
2017-06-15 15:41:31 [INFO] DnsProvider: Resolving m.irs01.com  Sending to /115.159.220.214
2017-06-15 15:41:31 [INFO] DnsProvider: Resolving rlog.video.qq.com  Sending to /115.159.220.214
2017-06-15 15:41:31 [INFO] DnsProvider: Resolving sdkconfig.video.qq.com  Sending to /115.159.220.214
2017-06-15 15:41:31 [INFO] DnsProvider: Resolving vv.video.qq.com  Sending to /115.159.220.214
2017-06-15 15:41:31 [INFO] DnsProvider: Resolving commdata.v.qq.com  Sending to /115.159.220.214
2017-06-15 15:41:30 [INFO] DnsProvider: Resolving android.rqd.qq.com  Sending to /115.159.220.214
2017-06-15 15:41:30 [INFO] DnsProvider: Resolving aoma.qq.com  Sending to /115.159.220.214
2017-06-15 15:41:30 [INFO] DnsProvider: Resolving omgmta1.qq.com  Sending to /115.159.220.214
2017-06-15 15:41:30 [INFO] DnsProvider: Resolving news.l.qq.com  Sending to /115.159.220.214
2017-06-15 15:41:30 [INFO] DnsProvider: Resolving av.video.qq.com  Sending to /115.159.220.214
2017-06-15 15:41:30 [INFO] DnsProvider: Resolving dp3.qq.com  Sending to /115.159.220.214
2017-06-15 15:41:30 [INFO] DnsProvider: Resolving mtrace.qq.com  Sending to /115.159.220.214

**Comment by PeratX** [comment]
已收到，正在分析。

**Comment by PeratX** [comment]
建议您尝试一下1.9.0版本

**Comment by JerryYangHub** [comment]
腾讯视频和Daedalus都是最新版。

**Comment by PeratX** [comment]
能描述一下怎么触发这个bug吗，代码和测试都看不出逻辑哪里有问题。

**Comment by PeratX** [comment]
https://github.com/iTXTech/Daedalus/commit/d29035f09ae1076a3e301b27d9a984733ca66728
能否给个联系方式，我把测试用APK发送给您。

**Comment by JerryYangHub** [comment]
qq741934824

**Comment by JerryYangHub** [comment]
触发情况就是打开腾讯视频app。。。过2s左右。Daedalus就自动被断开vpn。然后关闭了。

**Comment by JerryYangHub** [comment]
我录了个演示视频。[http://pan.baidu.com/s/1o8v5iA2](url)

**Comment by JerryYangHub** [comment]
我录了个演示视频。http://pan.baidu.com/s/1o8v5iA2

**Comment by cancelpj** [comment]
我的情况也一样。

**Comment by PeratX** [comment]
yep
