### ISSUE TITLE
使用中的小问题

### ISSUE THREAD

**Issue by vovoa17** [iTXTech/Daedalus#26]
系统 7.1.1 xperia xz premium
1. 当我在使用移动数据时切换到WLAN，程序VPN模式会自动停止
2. 程序运行一段时间之后，VPN模式也会自动停止
`2017-07-21 15:38:07 [INFO] Daedalus VPN service has stopped
2017-07-21 15:38:06 [ERROR] java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String java.lang.CharSequence.toString()' on a null object reference
	at de.measite.minidns.util.InetAddressUtil.ipv4From(InetAddressUtil.java:23)
	at org.itxtech.daedalus.provider.UdpDnsProvider.handleDnsRequest(UdpDnsProvider.java:317)
	at org.itxtech.daedalus.provider.UdpDnsProvider.readPacketFromDevice(UdpDnsProvider.java:208)
	at org.itxtech.daedalus.provider.UdpDnsProvider.process(UdpDnsProvider.java:150)
	at [org.itxtech.daedalus.service.DaedalusVpnService.run(DaedalusVpnService.java:237)]
	at java.lang.Thread.run(Thread.java:761)`

另外，在 #19 中我提到了一个泛解析问题，最后我发现域名能正确解析，是因为android.clients.google.com默认以HTTP方式连接，会被GFW重设，使用HTTPS正常连接

提一个小建议，只使用hosts/dnsmasq文件，而不设置服务器地址，便于切换网络时使用运营商的DNS

**Comment by vovoa17** [comment]
是网易云音乐的锅，一旦检测网络变动就会发送大量反向域请求，程序就崩溃了

**Comment by PeratX** [comment]
1.10 BETA似乎已经修复了问题

**Comment by vovoa17** [comment]
多谢，查询PTR记录已经不会崩溃了
2017-07-29 14:48:00 [INFO] Provider: Resolving nstool.netease.com Type: A Sending to /119.29.29.29
2017-07-29 14:48:00 [INFO] Provider: Resolving 197.160.111.59.in-addr.arpa Type: PTR Sending to /119.29.29.29
2017-07-29 14:47:59 [INFO] Provider: Resolving 197.160.111.59.in-addr.arpa Type: PTR Sending to /119.29.29.29
2017-07-29 14:47:59 [INFO] Provider: Resolving adash.man.aliyuncs.com Type: A Sending to /119.29.29.29
2017-07-29 14:47:58 [INFO] Provider: Resolving 197.160.111.59.in-addr.arpa Type: PTR Sending to /119.29.29.29

**Comment by vovoa17** [comment]
😂这个beta版什么时候转正上架play store？

**Comment by PeratX** [comment]
怕是不会了，现在风声太紧。

**Comment by zhangyz1997** [comment]
不转正的话想用岂不是还得自个儿编译?

**Comment by PeratX** [comment]
ssr都已经删库跑路了，各种撕逼人肉，我可不想被这样搞。┑(￣Д ￣)┍

**Comment by PeratX** [comment]
既然问题已经解决了，那我就close了。╮(╯▽╰)╭
