### ISSUE TITLE
Android Oreo中下载规则失败

### ISSUE THREAD

**Issue by LiarOnce** [iTXTech/Daedalus#61]
可能是因为Android Oreo更严格的权限导致，我看到应用权限中没有存储权限。

**Comment by LiarOnce** [comment]
![Screenshot_20180214-222655.png](https://i.loli.net/2018/02/14/5a8447330802b.png)

**Comment by LiarOnce** [comment]
以下是错误信息：
```
2018-02-14 22:20:52 [ERROR] java.io.FileNotFoundException: nullgooglehosts.hosts (Read-only file system)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:287)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:223)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:171)
	at org.itxtech.daedalus.fragment.RuleConfigFragment$RuleConfigHandler.handleMessage(RuleConfigFragment.java:404)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6494)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

2018-02-14 22:20:41 [INFO] Delete rule googlehosts/hosts
```

**Comment by PeratX** [comment]
emmmm
没有获取到路径信息吗

**Comment by LiarOnce** [comment]
@PeratX 主要是那个Read-only file system

**Comment by PeratX** [comment]
emmmm先等一下，Daedalus并不请求Sensors这个权限啊

**Comment by PeratX** [comment]
在以前的android中，存到自己应用目录下是不需要权限的

**Comment by LiarOnce** [comment]
Sensors 这个权限每个应用都有
貌似到8.1存到自己应用目录也要权限，总之严格了很多
（不是很懂Google

**Comment by PeratX** [comment]
我也不是很懂，我刚装了SDK 27的AVD发行卡成老狗而且不能上网。。。。

**Comment by LiarOnce** [comment]
8.1连应用安装权限都要一个个点🤣。。。。。。

**Comment by liyuhaolol** [comment]
作者没写动态运行时权限，只是提示让你去设置开启IO权限，可笑的是，作者没有在AndriodManifest中声明IO权限，233

**Comment by PeratX** [comment]
因为在之前版本中（7.x），写在Android/data下不需要权限

**Comment by PeratX** [comment]
已经查明，并不需要IO权限，换用OkHttp后正常下载

**Comment by PeratX** [comment]
如果遇到下载失败，请确认手机是否配置了IPv6并且可用，如果IPv6不可用请停用IPv6。
https://github.com/square/okhttp/issues/2021
