### ISSUE TITLE
dns查询方式使用tls时出现的问题

### ISSUE THREAD

**Issue by rhjdvsgsgks** [iTXTech/Daedalus#75]
2018-08-05 18:23:31 [DEBUG] DnsRequest: DnsMessage(33273 QUERY NO_ERROR query[qr=0] rd)
[Q: api.accuweather.com.	IN	A]
2018-08-05 18:23:31 [ERROR] javax.net.ssl.SSLHandshakeException: Connection closed by peer
	at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
	at com.android.org.conscrypt.SslWrapper.doHandshake(SslWrapper.java:374)
	at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:217)
	at com.android.org.conscrypt.ConscryptFileDescriptorSocket.waitForHandshake(ConscryptFileDescriptorSocket.java:468)
	at com.android.org.conscrypt.ConscryptFileDescriptorSocket.getOutputStream(ConscryptFileDescriptorSocket.java:455)
	at org.itxtech.daedalus.provider.TlsProvider.forwardPacket(TlsProvider.java:42)
	at org.itxtech.daedalus.provider.UdpProvider.handleDnsRequest(UdpProvider.java:222)
	at org.itxtech.daedalus.provider.Provider.readPacketFromDevice(Provider.java:188)
	at org.itxtech.daedalus.provider.TcpProvider.process(TcpProvider.java:112)
	at org.itxtech.daedalus.service.DaedalusVpnService.run(DaedalusVpnService.java:300)
	at java.lang.Thread.run(Thread.java:764)

**Comment by PeratX** [comment]
不发服务器配置我怎么知道你有什么问题
